name: Snyk Scan on Pull Request

on:
  pull_request:
    branches:
      - main # ou a branch padrão do seu projeto
    paths:
      - '**/package.json' # ou outro arquivo relevante de dependências

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (se for um projeto Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk Test
        run: snyk test

      - name: Upload Snyk Results as a GitHub Check
        uses: snyk/actions/upload-snyk-results@v1
